// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#ifndef PROTOBUF_base_2eproto__INCLUDED
#define PROTOBUF_base_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace tms {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_base_2eproto();
void protobuf_AssignDesc_base_2eproto();
void protobuf_ShutdownFile_base_2eproto();

class UserBaseInfo;
class TargetInfo;
class Targets;
class UTarget;

enum TargetType {
  TargetType_User = 0,
  TargetType_Group = 1
};
bool TargetType_IsValid(int value);
const TargetType TargetType_MIN = TargetType_User;
const TargetType TargetType_MAX = TargetType_Group;
const int TargetType_ARRAYSIZE = TargetType_MAX + 1;

const ::google::protobuf::EnumDescriptor* TargetType_descriptor();
inline const ::std::string& TargetType_Name(TargetType value) {
  return ::google::protobuf::internal::NameOfEnum(
    TargetType_descriptor(), value);
}
inline bool TargetType_Parse(
    const ::std::string& name, TargetType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TargetType>(
    TargetType_descriptor(), name, value);
}
// ===================================================================

class UserBaseInfo : public ::google::protobuf::Message {
 public:
  UserBaseInfo();
  virtual ~UserBaseInfo();

  UserBaseInfo(const UserBaseInfo& from);

  inline UserBaseInfo& operator=(const UserBaseInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserBaseInfo& default_instance();

  void Swap(UserBaseInfo* other);

  // implements Message ----------------------------------------------

  UserBaseInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserBaseInfo& from);
  void MergeFrom(const UserBaseInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string strAccountNo = 1;
  inline bool has_straccountno() const;
  inline void clear_straccountno();
  static const int kStrAccountNoFieldNumber = 1;
  inline const ::std::string& straccountno() const;
  inline void set_straccountno(const ::std::string& value);
  inline void set_straccountno(const char* value);
  inline void set_straccountno(const char* value, size_t size);
  inline ::std::string* mutable_straccountno();
  inline ::std::string* release_straccountno();
  inline void set_allocated_straccountno(::std::string* straccountno);

  // required string strNickName = 2;
  inline bool has_strnickname() const;
  inline void clear_strnickname();
  static const int kStrNickNameFieldNumber = 2;
  inline const ::std::string& strnickname() const;
  inline void set_strnickname(const ::std::string& value);
  inline void set_strnickname(const char* value);
  inline void set_strnickname(const char* value, size_t size);
  inline ::std::string* mutable_strnickname();
  inline ::std::string* release_strnickname();
  inline void set_allocated_strnickname(::std::string* strnickname);

  // required uint32 nFace = 3 [default = 0];
  inline bool has_nface() const;
  inline void clear_nface();
  static const int kNFaceFieldNumber = 3;
  inline ::google::protobuf::uint32 nface() const;
  inline void set_nface(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.UserBaseInfo)
 private:
  inline void set_has_straccountno();
  inline void clear_has_straccountno();
  inline void set_has_strnickname();
  inline void clear_has_strnickname();
  inline void set_has_nface();
  inline void clear_has_nface();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* straccountno_;
  ::std::string* strnickname_;
  ::google::protobuf::uint32 nface_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_base_2eproto();
  friend void protobuf_AssignDesc_base_2eproto();
  friend void protobuf_ShutdownFile_base_2eproto();

  void InitAsDefaultInstance();
  static UserBaseInfo* default_instance_;
};
// -------------------------------------------------------------------

class TargetInfo : public ::google::protobuf::Message {
 public:
  TargetInfo();
  virtual ~TargetInfo();

  TargetInfo(const TargetInfo& from);

  inline TargetInfo& operator=(const TargetInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TargetInfo& default_instance();

  void Swap(TargetInfo* other);

  // implements Message ----------------------------------------------

  TargetInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TargetInfo& from);
  void MergeFrom(const TargetInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string strAccountNo = 1;
  inline bool has_straccountno() const;
  inline void clear_straccountno();
  static const int kStrAccountNoFieldNumber = 1;
  inline const ::std::string& straccountno() const;
  inline void set_straccountno(const ::std::string& value);
  inline void set_straccountno(const char* value);
  inline void set_straccountno(const char* value, size_t size);
  inline ::std::string* mutable_straccountno();
  inline ::std::string* release_straccountno();
  inline void set_allocated_straccountno(::std::string* straccountno);

  // required string strNickName = 2;
  inline bool has_strnickname() const;
  inline void clear_strnickname();
  static const int kStrNickNameFieldNumber = 2;
  inline const ::std::string& strnickname() const;
  inline void set_strnickname(const ::std::string& value);
  inline void set_strnickname(const char* value);
  inline void set_strnickname(const char* value, size_t size);
  inline ::std::string* mutable_strnickname();
  inline ::std::string* release_strnickname();
  inline void set_allocated_strnickname(::std::string* strnickname);

  // required uint32 nFace = 3 [default = 0];
  inline bool has_nface() const;
  inline void clear_nface();
  static const int kNFaceFieldNumber = 3;
  inline ::google::protobuf::uint32 nface() const;
  inline void set_nface(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tms.TargetInfo)
 private:
  inline void set_has_straccountno();
  inline void clear_has_straccountno();
  inline void set_has_strnickname();
  inline void clear_has_strnickname();
  inline void set_has_nface();
  inline void clear_has_nface();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* straccountno_;
  ::std::string* strnickname_;
  ::google::protobuf::uint32 nface_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_base_2eproto();
  friend void protobuf_AssignDesc_base_2eproto();
  friend void protobuf_ShutdownFile_base_2eproto();

  void InitAsDefaultInstance();
  static TargetInfo* default_instance_;
};
// -------------------------------------------------------------------

class Targets : public ::google::protobuf::Message {
 public:
  Targets();
  virtual ~Targets();

  Targets(const Targets& from);

  inline Targets& operator=(const Targets& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Targets& default_instance();

  void Swap(Targets* other);

  // implements Message ----------------------------------------------

  Targets* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Targets& from);
  void MergeFrom(const Targets& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uTargetID = 1 [default = 0];
  inline bool has_utargetid() const;
  inline void clear_utargetid();
  static const int kUTargetIDFieldNumber = 1;
  inline ::google::protobuf::uint32 utargetid() const;
  inline void set_utargetid(::google::protobuf::uint32 value);

  // required .tms.TargetInfo TargetInfos = 2;
  inline bool has_targetinfos() const;
  inline void clear_targetinfos();
  static const int kTargetInfosFieldNumber = 2;
  inline const ::tms::TargetInfo& targetinfos() const;
  inline ::tms::TargetInfo* mutable_targetinfos();
  inline ::tms::TargetInfo* release_targetinfos();
  inline void set_allocated_targetinfos(::tms::TargetInfo* targetinfos);

  // @@protoc_insertion_point(class_scope:tms.Targets)
 private:
  inline void set_has_utargetid();
  inline void clear_has_utargetid();
  inline void set_has_targetinfos();
  inline void clear_has_targetinfos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::tms::TargetInfo* targetinfos_;
  ::google::protobuf::uint32 utargetid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_base_2eproto();
  friend void protobuf_AssignDesc_base_2eproto();
  friend void protobuf_ShutdownFile_base_2eproto();

  void InitAsDefaultInstance();
  static Targets* default_instance_;
};
// -------------------------------------------------------------------

class UTarget : public ::google::protobuf::Message {
 public:
  UTarget();
  virtual ~UTarget();

  UTarget(const UTarget& from);

  inline UTarget& operator=(const UTarget& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UTarget& default_instance();

  void Swap(UTarget* other);

  // implements Message ----------------------------------------------

  UTarget* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UTarget& from);
  void MergeFrom(const UTarget& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uTargetID = 1 [default = 0];
  inline bool has_utargetid() const;
  inline void clear_utargetid();
  static const int kUTargetIDFieldNumber = 1;
  inline ::google::protobuf::uint32 utargetid() const;
  inline void set_utargetid(::google::protobuf::uint32 value);

  // required uint32 uRight = 2 [default = 0];
  inline bool has_uright() const;
  inline void clear_uright();
  static const int kURightFieldNumber = 2;
  inline ::google::protobuf::uint32 uright() const;
  inline void set_uright(::google::protobuf::uint32 value);

  // optional bytes selfparam = 3;
  inline bool has_selfparam() const;
  inline void clear_selfparam();
  static const int kSelfparamFieldNumber = 3;
  inline const ::std::string& selfparam() const;
  inline void set_selfparam(const ::std::string& value);
  inline void set_selfparam(const char* value);
  inline void set_selfparam(const void* value, size_t size);
  inline ::std::string* mutable_selfparam();
  inline ::std::string* release_selfparam();
  inline void set_allocated_selfparam(::std::string* selfparam);

  // @@protoc_insertion_point(class_scope:tms.UTarget)
 private:
  inline void set_has_utargetid();
  inline void clear_has_utargetid();
  inline void set_has_uright();
  inline void clear_has_uright();
  inline void set_has_selfparam();
  inline void clear_has_selfparam();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 utargetid_;
  ::google::protobuf::uint32 uright_;
  ::std::string* selfparam_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_base_2eproto();
  friend void protobuf_AssignDesc_base_2eproto();
  friend void protobuf_ShutdownFile_base_2eproto();

  void InitAsDefaultInstance();
  static UTarget* default_instance_;
};
// ===================================================================


// ===================================================================

// UserBaseInfo

// required string strAccountNo = 1;
inline bool UserBaseInfo::has_straccountno() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserBaseInfo::set_has_straccountno() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserBaseInfo::clear_has_straccountno() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserBaseInfo::clear_straccountno() {
  if (straccountno_ != &::google::protobuf::internal::kEmptyString) {
    straccountno_->clear();
  }
  clear_has_straccountno();
}
inline const ::std::string& UserBaseInfo::straccountno() const {
  return *straccountno_;
}
inline void UserBaseInfo::set_straccountno(const ::std::string& value) {
  set_has_straccountno();
  if (straccountno_ == &::google::protobuf::internal::kEmptyString) {
    straccountno_ = new ::std::string;
  }
  straccountno_->assign(value);
}
inline void UserBaseInfo::set_straccountno(const char* value) {
  set_has_straccountno();
  if (straccountno_ == &::google::protobuf::internal::kEmptyString) {
    straccountno_ = new ::std::string;
  }
  straccountno_->assign(value);
}
inline void UserBaseInfo::set_straccountno(const char* value, size_t size) {
  set_has_straccountno();
  if (straccountno_ == &::google::protobuf::internal::kEmptyString) {
    straccountno_ = new ::std::string;
  }
  straccountno_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserBaseInfo::mutable_straccountno() {
  set_has_straccountno();
  if (straccountno_ == &::google::protobuf::internal::kEmptyString) {
    straccountno_ = new ::std::string;
  }
  return straccountno_;
}
inline ::std::string* UserBaseInfo::release_straccountno() {
  clear_has_straccountno();
  if (straccountno_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = straccountno_;
    straccountno_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void UserBaseInfo::set_allocated_straccountno(::std::string* straccountno) {
  if (straccountno_ != &::google::protobuf::internal::kEmptyString) {
    delete straccountno_;
  }
  if (straccountno) {
    set_has_straccountno();
    straccountno_ = straccountno;
  } else {
    clear_has_straccountno();
    straccountno_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string strNickName = 2;
inline bool UserBaseInfo::has_strnickname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserBaseInfo::set_has_strnickname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserBaseInfo::clear_has_strnickname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserBaseInfo::clear_strnickname() {
  if (strnickname_ != &::google::protobuf::internal::kEmptyString) {
    strnickname_->clear();
  }
  clear_has_strnickname();
}
inline const ::std::string& UserBaseInfo::strnickname() const {
  return *strnickname_;
}
inline void UserBaseInfo::set_strnickname(const ::std::string& value) {
  set_has_strnickname();
  if (strnickname_ == &::google::protobuf::internal::kEmptyString) {
    strnickname_ = new ::std::string;
  }
  strnickname_->assign(value);
}
inline void UserBaseInfo::set_strnickname(const char* value) {
  set_has_strnickname();
  if (strnickname_ == &::google::protobuf::internal::kEmptyString) {
    strnickname_ = new ::std::string;
  }
  strnickname_->assign(value);
}
inline void UserBaseInfo::set_strnickname(const char* value, size_t size) {
  set_has_strnickname();
  if (strnickname_ == &::google::protobuf::internal::kEmptyString) {
    strnickname_ = new ::std::string;
  }
  strnickname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UserBaseInfo::mutable_strnickname() {
  set_has_strnickname();
  if (strnickname_ == &::google::protobuf::internal::kEmptyString) {
    strnickname_ = new ::std::string;
  }
  return strnickname_;
}
inline ::std::string* UserBaseInfo::release_strnickname() {
  clear_has_strnickname();
  if (strnickname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = strnickname_;
    strnickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void UserBaseInfo::set_allocated_strnickname(::std::string* strnickname) {
  if (strnickname_ != &::google::protobuf::internal::kEmptyString) {
    delete strnickname_;
  }
  if (strnickname) {
    set_has_strnickname();
    strnickname_ = strnickname;
  } else {
    clear_has_strnickname();
    strnickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required uint32 nFace = 3 [default = 0];
inline bool UserBaseInfo::has_nface() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserBaseInfo::set_has_nface() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserBaseInfo::clear_has_nface() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserBaseInfo::clear_nface() {
  nface_ = 0u;
  clear_has_nface();
}
inline ::google::protobuf::uint32 UserBaseInfo::nface() const {
  return nface_;
}
inline void UserBaseInfo::set_nface(::google::protobuf::uint32 value) {
  set_has_nface();
  nface_ = value;
}

// -------------------------------------------------------------------

// TargetInfo

// required string strAccountNo = 1;
inline bool TargetInfo::has_straccountno() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TargetInfo::set_has_straccountno() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TargetInfo::clear_has_straccountno() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TargetInfo::clear_straccountno() {
  if (straccountno_ != &::google::protobuf::internal::kEmptyString) {
    straccountno_->clear();
  }
  clear_has_straccountno();
}
inline const ::std::string& TargetInfo::straccountno() const {
  return *straccountno_;
}
inline void TargetInfo::set_straccountno(const ::std::string& value) {
  set_has_straccountno();
  if (straccountno_ == &::google::protobuf::internal::kEmptyString) {
    straccountno_ = new ::std::string;
  }
  straccountno_->assign(value);
}
inline void TargetInfo::set_straccountno(const char* value) {
  set_has_straccountno();
  if (straccountno_ == &::google::protobuf::internal::kEmptyString) {
    straccountno_ = new ::std::string;
  }
  straccountno_->assign(value);
}
inline void TargetInfo::set_straccountno(const char* value, size_t size) {
  set_has_straccountno();
  if (straccountno_ == &::google::protobuf::internal::kEmptyString) {
    straccountno_ = new ::std::string;
  }
  straccountno_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TargetInfo::mutable_straccountno() {
  set_has_straccountno();
  if (straccountno_ == &::google::protobuf::internal::kEmptyString) {
    straccountno_ = new ::std::string;
  }
  return straccountno_;
}
inline ::std::string* TargetInfo::release_straccountno() {
  clear_has_straccountno();
  if (straccountno_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = straccountno_;
    straccountno_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TargetInfo::set_allocated_straccountno(::std::string* straccountno) {
  if (straccountno_ != &::google::protobuf::internal::kEmptyString) {
    delete straccountno_;
  }
  if (straccountno) {
    set_has_straccountno();
    straccountno_ = straccountno;
  } else {
    clear_has_straccountno();
    straccountno_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string strNickName = 2;
inline bool TargetInfo::has_strnickname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TargetInfo::set_has_strnickname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TargetInfo::clear_has_strnickname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TargetInfo::clear_strnickname() {
  if (strnickname_ != &::google::protobuf::internal::kEmptyString) {
    strnickname_->clear();
  }
  clear_has_strnickname();
}
inline const ::std::string& TargetInfo::strnickname() const {
  return *strnickname_;
}
inline void TargetInfo::set_strnickname(const ::std::string& value) {
  set_has_strnickname();
  if (strnickname_ == &::google::protobuf::internal::kEmptyString) {
    strnickname_ = new ::std::string;
  }
  strnickname_->assign(value);
}
inline void TargetInfo::set_strnickname(const char* value) {
  set_has_strnickname();
  if (strnickname_ == &::google::protobuf::internal::kEmptyString) {
    strnickname_ = new ::std::string;
  }
  strnickname_->assign(value);
}
inline void TargetInfo::set_strnickname(const char* value, size_t size) {
  set_has_strnickname();
  if (strnickname_ == &::google::protobuf::internal::kEmptyString) {
    strnickname_ = new ::std::string;
  }
  strnickname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TargetInfo::mutable_strnickname() {
  set_has_strnickname();
  if (strnickname_ == &::google::protobuf::internal::kEmptyString) {
    strnickname_ = new ::std::string;
  }
  return strnickname_;
}
inline ::std::string* TargetInfo::release_strnickname() {
  clear_has_strnickname();
  if (strnickname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = strnickname_;
    strnickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TargetInfo::set_allocated_strnickname(::std::string* strnickname) {
  if (strnickname_ != &::google::protobuf::internal::kEmptyString) {
    delete strnickname_;
  }
  if (strnickname) {
    set_has_strnickname();
    strnickname_ = strnickname;
  } else {
    clear_has_strnickname();
    strnickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required uint32 nFace = 3 [default = 0];
inline bool TargetInfo::has_nface() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TargetInfo::set_has_nface() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TargetInfo::clear_has_nface() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TargetInfo::clear_nface() {
  nface_ = 0u;
  clear_has_nface();
}
inline ::google::protobuf::uint32 TargetInfo::nface() const {
  return nface_;
}
inline void TargetInfo::set_nface(::google::protobuf::uint32 value) {
  set_has_nface();
  nface_ = value;
}

// -------------------------------------------------------------------

// Targets

// required uint32 uTargetID = 1 [default = 0];
inline bool Targets::has_utargetid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Targets::set_has_utargetid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Targets::clear_has_utargetid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Targets::clear_utargetid() {
  utargetid_ = 0u;
  clear_has_utargetid();
}
inline ::google::protobuf::uint32 Targets::utargetid() const {
  return utargetid_;
}
inline void Targets::set_utargetid(::google::protobuf::uint32 value) {
  set_has_utargetid();
  utargetid_ = value;
}

// required .tms.TargetInfo TargetInfos = 2;
inline bool Targets::has_targetinfos() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Targets::set_has_targetinfos() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Targets::clear_has_targetinfos() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Targets::clear_targetinfos() {
  if (targetinfos_ != NULL) targetinfos_->::tms::TargetInfo::Clear();
  clear_has_targetinfos();
}
inline const ::tms::TargetInfo& Targets::targetinfos() const {
  return targetinfos_ != NULL ? *targetinfos_ : *default_instance_->targetinfos_;
}
inline ::tms::TargetInfo* Targets::mutable_targetinfos() {
  set_has_targetinfos();
  if (targetinfos_ == NULL) targetinfos_ = new ::tms::TargetInfo;
  return targetinfos_;
}
inline ::tms::TargetInfo* Targets::release_targetinfos() {
  clear_has_targetinfos();
  ::tms::TargetInfo* temp = targetinfos_;
  targetinfos_ = NULL;
  return temp;
}
inline void Targets::set_allocated_targetinfos(::tms::TargetInfo* targetinfos) {
  delete targetinfos_;
  targetinfos_ = targetinfos;
  if (targetinfos) {
    set_has_targetinfos();
  } else {
    clear_has_targetinfos();
  }
}

// -------------------------------------------------------------------

// UTarget

// required uint32 uTargetID = 1 [default = 0];
inline bool UTarget::has_utargetid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UTarget::set_has_utargetid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UTarget::clear_has_utargetid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UTarget::clear_utargetid() {
  utargetid_ = 0u;
  clear_has_utargetid();
}
inline ::google::protobuf::uint32 UTarget::utargetid() const {
  return utargetid_;
}
inline void UTarget::set_utargetid(::google::protobuf::uint32 value) {
  set_has_utargetid();
  utargetid_ = value;
}

// required uint32 uRight = 2 [default = 0];
inline bool UTarget::has_uright() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UTarget::set_has_uright() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UTarget::clear_has_uright() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UTarget::clear_uright() {
  uright_ = 0u;
  clear_has_uright();
}
inline ::google::protobuf::uint32 UTarget::uright() const {
  return uright_;
}
inline void UTarget::set_uright(::google::protobuf::uint32 value) {
  set_has_uright();
  uright_ = value;
}

// optional bytes selfparam = 3;
inline bool UTarget::has_selfparam() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UTarget::set_has_selfparam() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UTarget::clear_has_selfparam() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UTarget::clear_selfparam() {
  if (selfparam_ != &::google::protobuf::internal::kEmptyString) {
    selfparam_->clear();
  }
  clear_has_selfparam();
}
inline const ::std::string& UTarget::selfparam() const {
  return *selfparam_;
}
inline void UTarget::set_selfparam(const ::std::string& value) {
  set_has_selfparam();
  if (selfparam_ == &::google::protobuf::internal::kEmptyString) {
    selfparam_ = new ::std::string;
  }
  selfparam_->assign(value);
}
inline void UTarget::set_selfparam(const char* value) {
  set_has_selfparam();
  if (selfparam_ == &::google::protobuf::internal::kEmptyString) {
    selfparam_ = new ::std::string;
  }
  selfparam_->assign(value);
}
inline void UTarget::set_selfparam(const void* value, size_t size) {
  set_has_selfparam();
  if (selfparam_ == &::google::protobuf::internal::kEmptyString) {
    selfparam_ = new ::std::string;
  }
  selfparam_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UTarget::mutable_selfparam() {
  set_has_selfparam();
  if (selfparam_ == &::google::protobuf::internal::kEmptyString) {
    selfparam_ = new ::std::string;
  }
  return selfparam_;
}
inline ::std::string* UTarget::release_selfparam() {
  clear_has_selfparam();
  if (selfparam_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = selfparam_;
    selfparam_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void UTarget::set_allocated_selfparam(::std::string* selfparam) {
  if (selfparam_ != &::google::protobuf::internal::kEmptyString) {
    delete selfparam_;
  }
  if (selfparam) {
    set_has_selfparam();
    selfparam_ = selfparam;
  } else {
    clear_has_selfparam();
    selfparam_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tms

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tms::TargetType>() {
  return ::tms::TargetType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_base_2eproto__INCLUDED
